### ISSUE TITLE
Handling of packageId for pre-DOI EML file

### ISSUE THREAD

**Issue by cgendreau** [gbif/registry#1]
Hi!

I'm trying to read an old EML file using `Dataset.parse` and I was wondering how to get the packageId if it's not a DOI?
The [setPackageId](https://github.com/gbif/registry/blob/master/registry-metadata/src/main/java/org/gbif/registry/metadata/parse/DatasetWrapper.java#L428) method will ignore the packageId if not a DOI but I have an old UUID (e.g. packageId="ada5d0b1-07de-4dc0-83d4-e312f0fb81cb/v2").

Maybe you assigned DOI to all datasets so I use should org.gbif.metadata.MetadataFactory from gbif-metadata-profile instead?

Regards

**Comment by kbraak** [comment]
The setPackageID is only trying to recognize packageIDs that are DOIs as per the DOI handling rules described here: http://dev.gbif.org/issues/browse/POR-2545?focusedCommentId=19310&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19310

The Dataset object ( https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/model/registry/Dataset.java ) has no packageID, since this is the identifier for the metadata document itself. 

The gbif-metadata-profile project is currently used exclusively by the IPT, and populates an EML object with a packageID. Before you use that though, maybe just consider creating a little parser method to get the packageID?
