### ISSUE TITLE
Linked dataset/search example returning unexpected results

### ISSUE THREAD

**Issue by tucotuco** [gbif/registry#110]
On the page https://www.gbif.org/developer/registry there is a link for DatasetSearchResult under the dataset/search GET method description. The link goes to:

http://api.gbif.org/v1/dataset/search?q=plant&amp;publishingCountry=AR

The results of that query include 1404 records with lots of different values of publishingCountry.  The following query does seem to function correctly:

http://api.gbif.org/v1/dataset/search?publishingCountry=AR

I have had similar problems with unexpected results with dataset/search queries, but figured this linked one might be a good place to start.

**Comment by marcos-lg** [comment]
The problem seems to be the escaping of the `&` in http://api.gbif.org/v1/dataset/search?q=plant&amp;publishingCountry=AR which makes the `publishingCountry` param to be ignored.

Besides that the API seems to work correctly:

https://api.gbif.org/v1/dataset/search?q=plant&publishingCountry=AR filters the publishing country correctly
