### ISSUE TITLE
pipelines - 61 steps in one attempt

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#153]
https://api.gbif-dev.org/v1/pipelines/history/f4971deb-ddd5-42e9-8f5b-5d8daa6f251e/38

has 61 steps. Given that there is only 4(?) steps in a pipeline there is a lot of repetition. Is this to be expected? It feels like something that could cause confusion? If it is intended, perhaps a little info box describing how to read this (if so please provide a help text that i can use)? All but one succeeded. The one that didn't succeed is still running (see [separate issue](https://github.com/gbif/registry/issues/150)).

**Comment by asturcon** [comment]
In DEV this can be expected because we always use the same datasets and very often we rerun the same processes with the same attempt for testing. 

The pipeline steps are ordered by started date in descending order. Usually, we're more interested in the last step of each StepType, so the others can be shown in UI in a way they look less important.
