### ISSUE TITLE
DOI regex is wrong

### ISSUE THREAD

**Issue by timrobertson100** [gbif/registry#154]
https://api.gbif.org/v1/dataset/e4f989d2-2dcb-4d3a-9886-95a337ff4c31

Returns
```
Illegal character in path at index 42: https://doi.org/10.1649/0010-065x(2001)055[0411:daposa]2.0.co;2
```

However DOI think it is correct.

**Comment by mdoering** [comment]
interesting. Maybe DOI and URL encoding clashes.
https://www.doi.org/doi_handbook/2_Numbering.html#2.2.3
> The DOI suffix shall consist of a character string of any length chosen by the registrant.

**Comment by mdoering** [comment]
https://www.doi.org/doi_handbook/2_Numbering.html#2.5.1

> DOI names may incorporate any printable characters from the Universal Character Set (UCS-2), of ISO/IEC 10646, which is the character set defined by Unicode. The character set encompasses most characters used in every major language written today. However, because of specific uses made of certain characters by some Internet technologies (the use of pointed brackets < > in xml for example), there may some effective restrictions in day-to-day use (see below).

> Neither the Handle System nor DOI system policies, nor any web use currently imaginable, impose any constraints on the suffix, outside of encoding (see below)

**Comment by asturcon** [comment]
I was checking this quickly and breaks when we try to create the URL from the DOI https://github.com/gbif/gbif-api/blob/5c8a777cb7d1408107a260e2ca614e8dc2117c19/src/main/java/org/gbif/api/model/common/DOI.java#L145

It breaks because the square brackets are reserved characters in URLs (see Character categories https://docs.oracle.com/javase/7/docs/api/java/net/URI.html).

Those characters should be escaped. I don't know how this DOI was created, but should we check that the DOIs are valid URLs before inserting them in the registry DB? or we accept anything and escape what is needed when we generate the URL?

**Comment by mike-podolskiy90** [comment]
> I was checking this quickly and breaks when we try to create the URL from the DOI https://github.com/gbif/gbif-api/blob/5c8a777cb7d1408107a260e2ca614e8dc2117c19/src/main/java/org/gbif/api/model/common/DOI.java#L145
> 
> It breaks because the square brackets are reserved characters in URLs (see Character categories https://docs.oracle.com/javase/7/docs/api/java/net/URI.html).
> 
> Those characters should be escaped. I don't know how this DOI was created, but should we check that the DOIs are valid URLs before inserting them in the registry DB? or we accept anything and escape what is needed when we generate the URL?

I think we need to apply the second approach

**Comment by asturcon** [comment]
Fixed in this commit in gbif-api https://github.com/gbif/gbif-api/commit/d2311adcf904fd5010952ba9de7d9ad6ca7ba1a3

It's now being tested in DEV.

**Comment by asturcon** [comment]
fixed and deployed in PROD
