### ISSUE TITLE
GrSciColl - multilingual

### ISSUE THREAD

**Issue by MortenHofft** [gbif/registry#177]
So far none of our entities support multilingual content. EML does support it as far as I know, but we do not. For some publishers, it is an important feature to be able to provide descriptions etc in multiple languages.
We have all along planned to have a multilingual interface, but content have always been one language (for the most part english). How far should we take internationalisation in GrSciColl?
```
{
  key: 123,
  title: {
    en: My collection,
    da: Min kollektion
  },
  ...
}
```

**Comment by kcopas** [comment]
I saw this in the laundry list. Could we establish a CrowdIn connection to facilitate translation?

**Comment by MortenHofft** [comment]
We could do so yes. I had imagined it being 100% in the control of the collection owners and up to them how to translate their content if they wanted it translated.
It feels wrong to me to ask the community to translate something without knowing if the source will change tomorrow?

**Comment by emeyke** [comment]
We will integrate with CD as soon as it is in prod and from our rather few initial discussions collection owners would want control over this. Which means collection records ought to be linked with GBIF organizations and operated under same user permissions.

**Comment by kcopas** [comment]
While I absolutely understand the sentiment here @MortenHofft : 

> It feels wrong to me to ask the community to translate something without knowing if the source will change tomorrow?

…in practice, this is literally how it goes. None of our web texts are immutable, nor should they be.

But it's important to note that our language communities have continued to add translations for new strings and update existing ones for revised ones. I'd like to introduce into evidence, Exhibit A, received from  Friday, 13 March 2020, 20:55 CET:

![IMG_3353](https://user-images.githubusercontent.com/12379236/76699728-9b0fc280-66b0-11ea-9e5f-81b0878b9fd8.jpg)

This is only possible because CrowdIn sends automated alerts to our volunteer translators that there are new or updated strings awaiting translation. We could not do this any other way, and with this functionality, I don't think we have to.

**Comment by MortenHofft** [comment]
True, it is quite impressive with the translations.

Either way, if we decide to do this, a lot of other things need to be implemented first, and those are unaffected by a later stage CrowdIn opt-in.

**Comment by MattBlissett** [comment]
The relevant issue for dataset/organization/node information being translated is this one: https://github.com/gbif/portal-feedback/issues/1549
