### ISSUE TITLE
"Appears in X Checklist datasets:" has disappeared

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#205]
"Appears in X Checklist datasets:" has disappeared.

See https://www.gbif.org/species/2435350, for example.

**Comment by MortenHofft** [comment]
@ahahn-gbif this also explains why GRIIS data no longer shows on species pages.

**Comment by timrobertson100** [comment]
> Should the CLB code be updated to index into ES instead?

I don't see any reason we need to do that right now.

**Comment by mdoering** [comment]
Yes, we still run a "dataset" index on Solr that clb updates, but does not use otherwise. It's meant for the registry to answer these kind of dataset by taxonKey questions.

**Comment by timrobertson100** [comment]
> Yes, we still run a "dataset" index on Solr that clb updates, but does not use otherwise. It's meant for the registry to answer these kind of dataset by taxonKey questions.

What process is that please, @mdoering ? We need to remove that from the deployment as there is no Solr registry index.

**Comment by mdoering** [comment]
[clb-analysis](http://mq.gbif.org:15672/#/queues/%2Fprod/clb-analysis), but let me check if that process does anything else. Shall I remove it from clb code?

**Comment by mdoering** [comment]
It does. It still needs to run to create metrics for CLB. I will remove the index updater from that code

**Comment by timrobertson100** [comment]
For reference - the new updating code is done [here](https://github.com/gbif/registry/blob/master/registry-search/src/main/java/org/gbif/registry/search/dataset/indexing/DatasetJsonConverter.java#L175) with the registry connecting through JDBC and issuing [this SQL](https://github.com/gbif/registry/blob/master/registry-search/src/main/java/org/gbif/registry/search/dataset/indexing/checklistbank/ChecklistbankPersistenceServiceImpl.java#L38).

**Comment by mdoering** [comment]
I've removed the code from CLB and released a new version for deploys that ignore the dataset index

**Comment by mdoering** [comment]
the `dataset` entry in all deploy configs still needs to be removed

**Comment by fmendezh** [comment]
This issue has been fixed for Checklists, it was a combination of improvements in the Elasticsearch index, worth mentioning:

1. The taxonKey fields had to be excluded from the _source field, otherwise, Elasticsearch loaded the document in memory before discarding the field (https://github.com/gbif/registry/commit/298efffb66a7da9b24b6f813e0d686b1cbc8b274#diff-c2da4097e5815a52dd2dff761d2a08c4R4).
2. Some fields used to score datasets were interpreted by Elasticsearch or its Java client as String/Keywords even when they were explicitly mapped to double, using wrapper (Double) classes seem to have fixed that behavior (https://github.com/gbif/registry/commit/298efffb66a7da9b24b6f813e0d686b1cbc8b274#diff-82243b851b32b10c733df5501c0a3681L256)
3. The Virtual Machine has been resized to use more CPU and RAM.
4. Sorting elements ASC 2X faster than sorting DESC for the default fields, for that the inverted score is stored in ES to allows sorting ASC (https://github.com/gbif/registry/commit/298efffb66a7da9b24b6f813e0d686b1cbc8b274#diff-82243b851b32b10c733df5501c0a3681R285)

https://github.com/gbif/registry/commit/298efffb66a7da9b24b6f813e0d686b1cbc8b274
