### ISSUE TITLE
Allow iDigBio editors to merge GRSciColl entities

### ISSUE THREAD

**Issue by marcos-lg** [gbif/registry#292]
This requires to create an IDIGBIO_GRSCICOLL_EDITOR role

**Comment by MattBlissett** [comment]
I haven't followed the discussion on this (i.e. I have no idea what it's about) but wouldn't something like `GRSCICOLL_MERGER` be a better name for the role? In case someone outside iDigBio needs the permission.

**Comment by marcos-lg** [comment]
Sorry, I should have explained the issue better.

Currently the merging service doesn't allow to merge iDigBio entities and now we were planning to allow it but only for users with the right permissions. It could actually be `IDIGBIO_GRSCICOLL_MERGER` since this role will only be used for this use case. 

Another option can be to extend the scopes of the editors to, for example, add permissions to modify only iDigBio entities (this could be extended in the future to other types of scopes like countries or other things like IH). This option will require more intrusive changes to the current scoping system but it could be a better solution for the long term.

Any thoughts on this? CC: @ManonGros

**Comment by ManonGros** [comment]
Thanks @marcos-lg! 
Extending the scopes would be really useful. I can definitely think of a few use cases for country scopes (and maybe IH, especially if they show interest in using our system in the future).
In this context, and iDigBio scope would be great!
How much work would it be?

Otherwise, if we remain on the ides of having a role (instead of the extended scope), then I think "editor" would make more sense than "merger" as we could use this role to allow other potential functions in the future.

**Comment by CatChapman** [comment]
Hi all!

Somewhat related, and please forgive me if this is answered elsewhere or if this question is better suited elsewhere.

For the machine tags in iDigBio entries, are these permission-restricted? i.e. can any editor on the Registry modify these tags, or is it restricted to those in a specific (e.g. iDigBio?) group?

I wonder because ideally at some point in the future we would like collections managers to have the option to update their own entries directly on the Registry, but I envision the risk of them modifying, intentionally or otherwise, the recordset tags and breaking functionality. (In addition to, of course, all the other barriers to getting data providers on board with modifying their own data - I foresee myself being the go-to editor for IDB data providers for quite some time. :) )

**Comment by marcos-lg** [comment]
Thanks @CatChapman. Since we're creating a new `IDIGBIO_GRSCICOLL_EDITOR` role we'll use it to only allow users with this role to modify the iDigBio machine tags.
