### ISSUE TITLE
IDIGBIO_EDITOR can click on delete for macthineTag even though it cannot delete machineTags 

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#315]
This is what happens when my iDigBio test user clicks on "delete" for a machineTag:
<img width="1132" alt="Screenshot 2021-02-23 at 16 00 35" src="https://user-images.githubusercontent.com/7677271/108862198-4a0e8b00-75f0-11eb-9cb2-f20ce68aea25.png">

**Comment by MortenHofft** [comment]
I'm unable to reproduce. Could you please describe the exact scopes and roles required and a link to a broken entity?

**Comment by ManonGros** [comment]
Example of broken entity: https://registry.gbif-uat.org/institution/fdee1b94-e933-4a6e-9a85-05cc39a085a6/machineTag
The roles of my test user (marie-test-editor):

- REGISTRY_EDITOR
- USER
- IDIGBIO_GRSCICOLL_EDITOR

(the scope doesn't seem to matter, I get the same without any scope).
Scopes

**Comment by MortenHofft** [comment]
I see it now as well. Also when not logged in.

DELETE to https://registry-api.gbif-uat.org/institution/fdee1b94-e933-4a6e-9a85-05cc39a085a6/machineTag/6183585?checkPermissionsOnly=true return statusCode 200

Everyone can apparently delete. Except they cannot when actually trying, but the permission check says they can.

**Comment by MortenHofft** [comment]
Solved: Any url will return statusCode 200 if not existing. And in this case "grscicoll" is missing from the URL.

This misunderstanding happens **often**. It would make sense not to return 200 when the user asks to delete something that do not exist. Since it isn't possible. You wouldn't be allowed to if trying, which is what the permission check should tell us.
