### ISSUE TITLE
Endorsement auto generate email: Update text body on endorsement email 

### ISSUE THREAD

**Issue by jlegind** [gbif/registry#339]
A node manager has requested that, in case there is no node manager or node manager email address, we rephrase the text from "doesn't have a Node Manager" to "doesn't have a registered GBIF Node Manager".

**Comment by ahahn-gbif** [comment]
suggest to extend that to ""doesn't have a registered GBIF Participant Node Manager"

**Comment by ahahn-gbif** [comment]
Background: confusion of prospective publishers, registering for endorsement through OBIS, caused by the confirmation mail. OBIS is a special case, still handling endorsements even though not an official GBIF Node. Mails do not get auto-forwarded for endorsement and are handled manually by helpdesk. The publisher gets confused by the message though, because OBIS, too, is a network of nodes, and has a Node Manager. Clarifying the GBIF context of the message would hopefully prevent the confusion between OBIS nodes and GBIF nodes on the publisher side, without causing irritation in other cases.
