### ISSUE TITLE
GRSciColl - could lookup system work with GRSciColl URLs?

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#410]
Right now, if a publisher is providing the URL to a GRSciColl entity, it gives no match:
https://api.gbif.org/v1/grscicoll/lookup?collectionId=https://www.gbif.org/grscicoll/collection/02bec4e3-2cd7-46f3-955e-46f9b802643d
But there is an exact match if the UUID only is provided:
https://api.gbif.org/v1/grscicoll/lookup?collectionId=02bec4e3-2cd7-46f3-955e-46f9b802643d

Is there a way to allow matching for the URLs as well?

**Comment by marcos-lg** [comment]
I think that the best would be to add that URL as an identifier of the collection.

**Comment by leo-buitrago** [comment]
Thanks for the clarification @marcos-lg . In that case, we have to add the URL identifier manually for each collection and institution and everything will work nicely (e.g. https://www.gbif.org/grscicoll/collection/02bec4e3-2cd7-46f3-955e-46f9b802643d). How could we know the difference between all the identifiers available on the GBIF Registry for collections and institutions? For instance, how do we know the differences between a GRSCICOLL_ID and a GRSCICOLL_URI?
![Screen Shot 2022-03-18 at 12 45 06 PM](https://user-images.githubusercontent.com/61566113/159055926-d5cc7dfe-85eb-4073-8cfd-3754c4978ffc.png)

**Comment by marcos-lg** [comment]
For the lookup to work it should be any type but GRSCICOLL_ID. I think we removed it because it mostly contains numbers that are not very meaningful. Those numbers are database IDs that were used in the old GRSCICOLL before we migrated it to GBIF.

GRSCICOLL_URI is used for cool URIs but I think these URLs could fit there. Any thoughts @ManonGros ?

**Comment by ManonGros** [comment]
Thanks @marcos-lg, I think using `GRSCICOLL_URI` for this purpose would be fine.

I will try to check if anyone is using `GRSCICOLL_ID` for occurrence linkage to GRSciColl before we decide to delete this identifier type.

**Comment by ManonGros** [comment]
@marcos-lg would it be possible to implement this change?

**Comment by marcos-lg** [comment]
Just checked and it's actually implemented. And the example provided in the description seems to work. Not sure when this was done or if the reason for the non-match was something else.

**Comment by EstebanMH-SiB** [comment]
It would be nice if this can be implemented and work only with the URL, without the need to add an additional identifier.

I made a test with a couple of our collections and is still not working with the full URL [https://api.gbif.org/v1/grscicoll/lookup?collectionId=https://www.gbif.org/grscicoll/collection/685298f2-0bc1-4e44-b2d5-d9760574644e](https://api.gbif.org/v1/grscicoll/lookup?collectionId=https://www.gbif.org/grscicoll/collection/685298f2-0bc1-4e44-b2d5-d9760574644e), only with the UUID [https://api.gbif.org/v1/grscicoll/lookup?collectionId=685298f2-0bc1-4e44-b2d5-d9760574644e](https://api.gbif.org/v1/grscicoll/lookup?collectionId=685298f2-0bc1-4e44-b2d5-d9760574644e). No idea why the original one is working.

**Comment by marcos-lg** [comment]
The original one works because the collection has the URL portal added as an identifier.

I don't think we should use the full URLs in the lookup since those URLs are not real identifiers, mainly because they could change. For example, that URL is different depending on the language(https://www.gbif.org/es/grscicoll/collection/685298f2-0bc1-4e44-b2d5-d9760574644e) or could be written slightly different(with http instead or https). 

Therefore, that's why the lookup doesn't use them. It uses the UUID because that's unique and can act as an identifier. But for some specific URLs I suggest adding them as identifiers in the collection(as in the original example).

**Comment by ManonGros** [comment]
@marcos-lg I know this wouldn't be very robust but maybe we could have some sort of regular expression and interpret stuff like interpret the ULRs with `gbif.org`, `grscicoll` and a UUID in them?

The problem with data providers just having to give the UUID is that for the users, the context is lacking. The users don't know where that UUID comes from. It is very cryptic.
At lease with a URL, even without being aware of GRSciColl, users can click on the link and see that this institutionID means.

**Comment by marcos-lg** [comment]
I deployed to production.

This seems to work: https://api.gbif.org/v1/grscicoll/lookup?collectionId=https://www.gbif.org/grscicoll/collection/685298f2-0bc1-4e44-b2d5-d9760574644e

For the interpreted data, the cache needs to be cleaned(which will happen tomorrow) and then the datasets need to be reinterpreted.
