### ISSUE TITLE
GRSciColl - LSIDs don't resolve

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#420]
This was pointed out by one of our publishers.
GRSciColl LSIDs don't resolve. For example, the LSID for this institution https://www.gbif.org/grscicoll/institution/a90ba963-9569-4b96-8d56-452aa7b83f75 is `urn:lsid:biocol.org:col:34984`. When added to a resolver: http://lsid.info/urn:lsid:biocol.org:col:34984, it gets this error:
```
Error 501:
The LSID urn:lsid:biocol.org:col:34984 cannot be resolved.  The error is:

	DNS lookup for SRV record for biocol.org failed.

For more information on LSIDs, see www.lsid.info.
```
This also means that the clickable links on the GBIF portal aren't working either: https://www.gbif.org/occurrence/2849494499

**Comment by mcruz-umich** [comment]
Hey thanks for fixing that! After reporting this issue, I decided to use the GRSciColl url instead which then led me to this other [already reported] issue: https://github.com/gbif/registry/issues/410

Do you recommend using the urn:lsid instead of the GRSciColl URL now that this issue is resolved?
I know from this article that that was the preferred ranking order:
https://www.gbif.org/faq?question=how-can-i-improve-the-matching-of-occurrence-records-with-grscicoll

Thanks
