### ISSUE TITLE
Cannot find out why two entries can't be merged - GRSciColl

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#429]
I am trying to merge this entry (https://registry.gbif.org/institution/42dbf750-5534-4f74-bf8b-c1a4a390446f) with this one (https://registry.gbif.org/institution/801cc29b-677e-41fc-ae40-040b80dd632c). But I keep getting an error message even though I thought I removed the email addresses from the entry I want [to delete](https://registry.gbif.org/institution/42dbf750-5534-4f74-bf8b-c1a4a390446f).
<img width="491" alt="Screenshot 2022-08-08 at 14 25 06" src="https://user-images.githubusercontent.com/7677271/183417866-61bbedea-3e72-428a-9675-e9930d7aa6b2.png">

@marcos-lg could you take a look? Did I miss something? thanks!

**Comment by marcos-lg** [comment]
I checked it and it turns out that the problem is the collection of the institution(https://registry.gbif.org/collection/edcd7817-ac5f-47d8-bb43-fb1f1d751f93). 

During the merge it tries to move the collections to the new institution and the email validation fails. This shouldn't happen because all the emails should be correct but I added the email validation only some months ago so there are still some wrong emails in the institutions/collections/contacts. Some months ago I had also added the validation to the IH sync not to bring more wrong emails.
