### ISSUE TITLE
User permissions scope seem changed but I don't remember changing it

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#464]
It is the second time it happens this week.

On helpdesk, I am asked to add some organizations to some usernames. However, when I check the registry, I can see that the account associated with the username already published a dataset for this organization even though isn’t in their permission scope. How is it possible?

For example, the [Virginia Military Institute](https://registry.gbif.org/organization/1b7411cb-03d2-4c8e-9c3c-0b95ac6b5e43) already published a dataset via symb-seinet: https://registry.gbif.org/dataset/d3cda990-8384-4865-9b3a-6017377e08bc and yet it seems that the organization isn’t in the permission scope of symb-seinet.
The same thing happened to symb-macroalgae and the San Diego Natural History Museum (which I had to add to the scope yesterday).

Did someone remove permissions at some point? Unless something else happened?

**Comment by marcos-lg** [comment]
I was checking the [code](https://github.com/gbif/registry/blob/69440f8a58c15a6f275b2d855f4fb7dc37335797/registry-security/src/main/java/org/gbif/registry/security/EditorAuthorizationServiceImpl.java#L211) and the user has permissions to modify the organization of the installation(https://registry.gbif.org/organization/96710dc8-fecb-440d-ae3e-c34ae8a9616f) and that's why it is allowed.

**Comment by ManonGros** [comment]
Thanks @marcos-lg Is there a way to find out if this is what happened there? Was the dataset created under a different institution?

**Comment by ahahn-gbif** [comment]
Without understanding the details, that sounds plausible. 

Since dataset hosting is a thing also for non-IPT installations, this would then in a second step require following the permissions management, that is: if the registered user of the installation (like symb-seinet) is authorized to a different organization, then (but only then) publishing and registering datasets under their name is permitted. Did I get that right?

**Comment by ManonGros** [comment]
FYI I am adding permissions for the user I mentioned in this issue.

**Comment by marcos-lg** [comment]
Deployed to PROD
