### ISSUE TITLE
GRSciColl - cannot apply this update suggestion

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#500]
https://registry.gbif.org/collection/a54e0bb4-6191-4615-a28a-1998d7045c15?suggestionId=1080

I don't know why, it either gives me an error if I click directly on the apply button or if I show it in the form and click apply it looks as if it goes through but the changes don't show. Please help, thanks!

**Comment by marcos-lg** [comment]
I had to do some tweaks in the DB to apply it. It's because the other day I did some changes related to this issue https://github.com/gbif/registry/issues/495 not to remove trailing spaces in strings, and in this case the address province was set as an empty string and that is not allowed in the DB. I'm going to fix it in the API not to have more cases like this.
