### ISSUE TITLE
GRSciColl lookup give unexpected result

### ISSUE THREAD

**Issue by ManonGros** [gbif/registry#533]
@marcos-lg 

This call gives me an exact fact for a collection:
https://api.gbif.org/v1/grscicoll/lookup?institutionCode=BBM&institutionId=urn:lsid:biocol.org:col:15106&collectionId=http://grscicoll.org/institution/university-british-columbia-botany-department

but adding the collection code doesn't give me a match:
https://api.gbif.org/v1/grscicoll/lookup?institutionCode=BBM&institutionId=urn:lsid:biocol.org:col:15106&collectionId=http://grscicoll.org/institution/university-british-columbia-botany-department&collectionCode=UBC

I thought that if the identifier is provided, this is what we privileged?
Shouldn't we have an exact match?

**Comment by marcos-lg** [comment]
Both matches are considered exact because they both belong the institution and both have that code(the main code in one and the alternative one in the other):

[https://api.gbif.org/v1/grscicoll/lookup?institutionCode=BBM&institutionId=urn:lsid[…]ish-columbia-botany-department&collectionCode=UBC&verbose=true](https://api.gbif.org/v1/grscicoll/lookup?institutionCode=BBM&institutionId=urn:lsid:biocol.org:col:15106&collectionId=http://grscicoll.org/institution/university-british-columbia-botany-department&collectionCode=UBC&verbose=true)

But the lookup should be able to disambiguate these cases and choose the one whose Id matches.

I'll fix it.

**Comment by marcos-lg** [comment]
Deployed to production. 

The cache needs to be cleaned before reprocessing the datasets but the scheduled cleaning will happen tomorrow in the morning.
