### ISSUE TITLE
A GRSciColl suggestion link returns with "Entity not found"

### ISSUE THREAD

**Issue by ckotwn** [gbif/registry#620]
The error is with this link https://registry.gbif.org/collection/create?suggestionId=2053.

While logged in, twice of "Entity not found for uri: /" was shown as notifications on the top right after the browser (Safari) attempted to open it.

An empty create form was given at the end of page loading.

Normally, a suggestion form is expected.

![Screenshot 2024-09-15 at 22 28 29](https://github.com/user-attachments/assets/881072c7-69f0-4984-ab8c-711ac476fdb9)

**Comment by ahakanzn** [comment]
Hi, It appears that there was a problem with some suggestions that were incorrectly created by ih-sync, which we have since deleted. However, the correct versions of these suggestions should have been created today.

Please check the suggestions created today to see if you can find the relevant ones. If you encounter any further issues or have questions about specific suggestions, feel free to reach out, and I’ll do my best to assist you.
