### ISSUE TITLE
modified parametre bug

### ISSUE THREAD

**Issue by CecSve** [gbif/registry#639]
Feedback from: https://discourse.gbif.org/t/registry-api-bug/5425 

> I have noticed there is a bug in the Registry API endpoint https://api.gbif.org/v1/dataset (documented here [Registry API :: Technical Documentation](https://techdocs.gbif.org/en/openapi/v1/registry#/Datasets/listDatasets)). According to the documentation the parameter modified should support wildcards in the form of omitted values, for example &modified=2024-09-10, or &modified=,2024-09-10.
> 
> You can see that when comparing output for https://api.gbif.org/v1/dataset?type=occurrence&modified=2024-09-10,2024-10-18, which returns 1961 results, and https://api.gbif.org/v1/dataset?type=occurrence&modified=2024-09-10, which returns 20 results, we would expect it to return an equal or larger amount of results, as it has the open end of the range.
> 
> The form https://api.gbif.org/v1/dataset?modified=,2024-10-18 does not work at all and returns status 400.
> 
> Additionally, the data parameter seems to be accepted as and expecting year-moth-day (throws an error if I try with 13 for month) but processed on the server when returning results as year-day-month. This could explain the issues above.

**Comment by MattBlissett** [comment]
A `*` to mark the end of the range is required, unfortunately it has been converted to italic text in the documentation.  This will be fixed in the next release. 

20 results for https://api.gbif.org/v1/dataset?type=occurrence&modified=2024-09-10 or https://api.gbif.org/v1/dataset?type=occurrence&modified=2024-09-10%2C (trailing comma escaped so GitHub links correctly) are the ones modified on that day only.

https://api.gbif.org/v1/dataset?type=occurrence&modified=2024-09-10%2C%2A (trailing `,*`) has 7909 results.

https://api.gbif.org/v1/dataset?type=occurrence&modified=%2A%2C2024-09-10 has 41929 results.

**Comment by MattBlissett** [comment]
Fixed in https://github.com/gbif/registry/commit/fac4f5e45bf1b4f4f90f04ac38904b0cd8fb5dd0

**Comment by smith558** [comment]
> A `*` to mark the end of the range is required, unfortunately it has been converted to italic text in the documentation. This will be fixed in the next release.
> 
> 20 results for https://api.gbif.org/v1/dataset?type=occurrence&modified=2024-09-10 or https://api.gbif.org/v1/dataset?type=occurrence&modified=2024-09-10%2C (trailing comma escaped so GitHub links correctly) are the ones modified on that day only.
> 
> https://api.gbif.org/v1/dataset?type=occurrence&modified=2024-09-10%2C%2A (trailing `,*`) has 7909 results.
> 
> https://api.gbif.org/v1/dataset?type=occurrence&modified=%2A%2C2024-09-10 has 41929 results.

Understood! Thank you very much for looking into this for me. 🙂
